// Rich per-agent data, modelled on an agent-directory detail page.
export const AGENTS = [
  {
    name: 'HR Agent',
    slug: 'hr-agent',
    category: 'HR',
    icon: '👥',
    accent: '#F5C010',
    url: 'https://ai.arttechgroup.com:7777/hr-agent/',
    tag: 'Agent',
    rating: 4.6,
    short: 'Automate hiring and everyday HR workflows in plain English.',
    tagline: 'Automate hiring and HR operations with an AI agent that understands plain English.',
    tags: [{ label: 'Featured', type: 'green' }, { label: 'Agent', type: 'blue' }],
    whoFor: 'HR teams, recruiters and people-ops leaders who want to cut manual work and respond to employees faster.',
    whatYouGet: 'An always-on assistant that screens candidates, answers employee questions, and handles onboarding and policy lookups.',
    howItWorks: 'Connect your HR data and job posts, then simply ask in natural language — the agent screens, drafts and answers using your own policies.',
    featureGroups: [
      { title: 'Recruiting', items: ['Automated candidate screening', 'Resume ranking & shortlisting', 'Interview scheduling support'] },
      { title: 'Employee Support', items: ['24/7 policy Q&A', 'Guided onboarding', 'Leave & benefits lookups'] },
    ],
    useCases: [
      { title: 'Faster candidate screening', desc: 'Shortlist the best applicants from hundreds of resumes in minutes.', industry: 'Recruiting' },
      { title: 'Employee self-service', desc: 'Staff get instant, accurate answers to HR questions any time.', industry: 'People Ops' },
      { title: 'Streamlined onboarding', desc: 'Walk new hires through paperwork, policies and first-week tasks.', industry: 'HR' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'HR & Recruiting'],
      ['Complexity', 'Low'], ['Pricing', 'Free option'],
    ],
  },
  {
    name: 'Cold Email Generator',
    slug: 'coldemail',
    category: 'Sales',
    icon: '✉️',
    accent: '#FBD75B',
    url: 'https://ai.arttechgroup.com:7777/coldemail/',
    tag: 'Generative',
    rating: 4.5,
    short: 'Generate personalized, high-converting outreach at scale.',
    tagline: 'Write personalized, high-converting cold emails in seconds — at scale.',
    tags: [{ label: 'New', type: 'green' }, { label: 'Generative', type: 'blue' }],
    whoFor: 'Sales, growth and founders who need consistent, personalized outreach without spending hours writing.',
    whatYouGet: 'A generator that crafts tailored emails, controls tone and templates, and builds smart follow-up sequences.',
    howItWorks: 'Paste a prospect or list and describe your offer — the agent drafts personalized emails and ready-to-send sequences.',
    featureGroups: [
      { title: 'Generation', items: ['Personalized at scale', 'Tone & style control', 'Reusable templates'] },
      { title: 'Outreach', items: ['Multi-step follow-ups', 'Subject-line variants', 'A/B-ready copy'] },
    ],
    useCases: [
      { title: 'Outbound campaigns', desc: 'Spin up a personalized campaign for a whole prospect list.', industry: 'Sales' },
      { title: 'Founder outreach', desc: 'Reach investors and partners with sharp, tailored emails.', industry: 'Startups' },
      { title: 'Re-engagement', desc: 'Win back cold leads with relevant follow-up sequences.', industry: 'Growth' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'Sales & Growth'],
      ['Complexity', 'Low'], ['Pricing', 'Free option'],
    ],
  },
  {
    name: 'Fintech Chatbot',
    slug: 'chatbot',
    category: 'Customer Service',
    icon: '💬',
    accent: '#E0A40C',
    url: 'https://ai.arttechgroup.com:7777/chatbot/',
    tag: 'Chatbot',
    rating: 4.7,
    short: 'Secure conversational AI built for fintech support.',
    tagline: 'A secure, always-on conversational assistant purpose-built for fintech.',
    tags: [{ label: 'Live', type: 'green' }, { label: 'Chatbot', type: 'blue' }],
    whoFor: 'Fintech and banking teams that need compliant, 24/7 customer support that can handle sensitive queries.',
    whatYouGet: 'A conversational assistant that answers customer questions, handles transactions and resolves multi-intent conversations.',
    howItWorks: 'Connect your product knowledge and policies — the bot responds securely, escalating to humans when needed.',
    featureGroups: [
      { title: 'Conversations', items: ['24/7 customer support', 'Multi-intent handling', 'Human handoff'] },
      { title: 'Security', items: ['Secure transaction queries', 'Compliance-aware replies', 'Audit logging'] },
    ],
    useCases: [
      { title: 'Customer support', desc: 'Resolve common queries instantly, reducing ticket volume.', industry: 'Fintech' },
      { title: 'Transaction help', desc: 'Guide users through payments, transfers and statements.', industry: 'Banking' },
      { title: 'Onboarding & KYC', desc: 'Answer onboarding questions and walk users through steps.', industry: 'Finance' },
    ],
    specs: [
      ['Deployment', 'Web / Embed'], ['Availability', 'Cloud'], ['Audience', 'Fintech'],
      ['Complexity', 'Medium'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'Unified Chatbot',
    slug: 'unified-chat',
    category: 'Customer Service',
    icon: '🤖',
    accent: '#FFD43B',
    url: 'https://ai.arttechgroup.com:7777/unified-chat',
    tag: 'Chatbot',
    rating: 4.6,
    short: 'One intelligent assistant across all of your channels.',
    tagline: 'Bring every conversation into one intelligent, context-aware assistant.',
    tags: [{ label: 'Featured', type: 'green' }, { label: 'Chatbot', type: 'blue' }],
    whoFor: 'Teams running support across multiple channels who want one consistent assistant and knowledge base.',
    whatYouGet: 'A single assistant that works across channels, shares one knowledge base, and keeps context everywhere.',
    howItWorks: 'Connect your channels and knowledge sources — the assistant serves consistent answers across all of them.',
    featureGroups: [
      { title: 'Omnichannel', items: ['One bot, every channel', 'Consistent answers', 'Context carries over'] },
      { title: 'Knowledge', items: ['Shared knowledge base', 'Live source sync', 'Smart routing'] },
    ],
    useCases: [
      { title: 'Unified support', desc: 'Answer customers the same way on web, chat and more.', industry: 'Support' },
      { title: 'Internal helpdesk', desc: 'Give employees one place to ask anything.', industry: 'Operations' },
      { title: 'Knowledge hub', desc: 'Turn scattered docs into instant answers.', industry: 'Enterprise' },
    ],
    specs: [
      ['Deployment', 'Web / Embed'], ['Availability', 'Cloud'], ['Audience', 'Enterprise'],
      ['Complexity', 'Medium'], ['Pricing', 'Free option'],
    ],
  },
  {
    name: 'Art Intelligence Platform',
    slug: 'art-intelligence',
    category: 'Research & Analysis',
    icon: '📊',
    accent: '#C8920A',
    url: 'https://ai.arttechgroup.com:7777/art-intelligence/dashboard',
    tag: 'Platform',
    rating: 4.8,
    short: 'Turn enterprise data into decisions with live analytics.',
    tagline: 'Turn raw enterprise data into decisions with real-time analytics and insights.',
    tags: [{ label: 'Featured', type: 'green' }, { label: 'Platform', type: 'blue' }],
    whoFor: 'Leaders and analysts who need a single, real-time view of their data to make faster decisions.',
    whatYouGet: 'A platform with real-time analytics, customizable dashboards and actionable, AI-generated insights.',
    howItWorks: 'Connect your data sources and build dashboards — the platform surfaces trends and insights automatically.',
    featureGroups: [
      { title: 'Analytics', items: ['Real-time metrics', 'Custom dashboards', 'Drill-down views'] },
      { title: 'Intelligence', items: ['AI-generated insights', 'Anomaly detection', 'Forecasting'] },
    ],
    useCases: [
      { title: 'Executive dashboards', desc: 'Give leadership a live view of the business.', industry: 'Enterprise' },
      { title: 'Operational reporting', desc: 'Replace manual reports with automated dashboards.', industry: 'Operations' },
      { title: 'Decision support', desc: 'Spot trends and act before they become problems.', industry: 'Strategy' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'Enterprise'],
      ['Complexity', 'Medium'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'FintechOps',
    slug: 'fintechops',
    category: 'Financial Services',
    icon: '⚙️',
    accent: '#EAB308',
    url: 'https://fintechops-arttechgroup.pages.dev/',
    tag: 'Operations',
    rating: 4.5,
    short: 'Automate and orchestrate your financial operations.',
    tagline: 'Streamline and orchestrate financial operations end-to-end.',
    tags: [{ label: 'Live', type: 'green' }, { label: 'Operations', type: 'blue' }],
    whoFor: 'Finance and operations teams that want to automate manual processes and monitor them in one place.',
    whatYouGet: 'Workflow automation, reconciliation and live operations monitoring across your financial processes.',
    howItWorks: 'Define your workflows and connect systems — FintechOps automates steps and flags exceptions in real time.',
    featureGroups: [
      { title: 'Automation', items: ['Workflow automation', 'Automated reconciliation', 'Exception handling'] },
      { title: 'Monitoring', items: ['Live ops dashboards', 'Alerts & SLAs', 'Audit trail'] },
    ],
    useCases: [
      { title: 'Reconciliation', desc: 'Match transactions automatically and surface mismatches.', industry: 'Finance' },
      { title: 'Process automation', desc: 'Remove repetitive manual steps from operations.', industry: 'Operations' },
      { title: 'Ops monitoring', desc: 'Track financial workflows live and catch issues early.', industry: 'Fintech' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'Finance Ops'],
      ['Complexity', 'Medium'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'Scheme Compliance Portal',
    slug: 'scheme-compliance-art',
    category: 'Financial Services',
    icon: '🛡️',
    accent: '#D9A41A',
    url: 'https://ai.arttechgroup.com:7777/scheme-compliance-art/login',
    tag: 'Compliance',
    rating: 4.7,
    short: 'End-to-end scheme compliance management — ART edition.',
    tagline: 'End-to-end scheme compliance management — the ART edition.',
    tags: [{ label: 'Secure', type: 'green' }, { label: 'Compliance', type: 'blue' }],
    whoFor: 'Compliance and risk teams managing schemes who need to track obligations and stay audit-ready.',
    whatYouGet: 'A portal to track compliance obligations, generate audit-ready reports and stay ahead of requirements.',
    howItWorks: 'Configure your schemes and obligations — the portal tracks status, deadlines and produces reports on demand.',
    featureGroups: [
      { title: 'Compliance', items: ['Obligation tracking', 'Deadline reminders', 'Status dashboards'] },
      { title: 'Reporting', items: ['Audit-ready reports', 'Evidence management', 'Role-based access'] },
    ],
    useCases: [
      { title: 'Obligation tracking', desc: 'Keep every requirement and deadline in one place.', industry: 'Compliance' },
      { title: 'Audit readiness', desc: 'Generate audit-ready reports in a few clicks.', industry: 'Risk' },
      { title: 'Scheme management', desc: 'Manage multiple schemes with role-based control.', industry: 'Governance' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'Compliance & Risk'],
      ['Complexity', 'Medium'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'Chargeback Management System',
    slug: 'chargeback-management-system',
    category: 'Financial Services',
    icon: '💳',
    accent: '#F5C010',
    url: 'https://chargeback-management-system.pages.dev/',
    tag: 'Finance',
    rating: 4.6,
    short: 'Track, manage and resolve payment chargebacks end-to-end.',
    tagline: 'Manage every chargeback from one place — track disputes, organize evidence and resolve cases on time.',
    tags: [{ label: 'New', type: 'green' }, { label: 'Finance', type: 'blue' }],
    whoFor: 'Finance, payments and risk teams who need to handle chargebacks and disputes without losing track of deadlines.',
    whatYouGet: 'A system to log disputes, manage evidence, monitor status and resolve chargebacks faster.',
    howItWorks: 'Log incoming chargebacks, attach evidence and track each case through to resolution from a single dashboard.',
    featureGroups: [
      { title: 'Disputes', items: ['Case logging & tracking', 'Evidence management', 'Deadline reminders'] },
      { title: 'Insights', items: ['Status dashboards', 'Win-rate reporting', 'Reason-code analysis'] },
    ],
    useCases: [
      { title: 'Dispute resolution', desc: 'Manage every chargeback case from intake to outcome.', industry: 'Payments' },
      { title: 'Evidence management', desc: 'Keep all supporting documents organized per case.', industry: 'Finance' },
      { title: 'Loss reduction', desc: 'Improve win rates with reason-code insights and reporting.', industry: 'Risk' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'Finance & Payments'],
      ['Complexity', 'Medium'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'IRIS',
    slug: 'incident-triage-rca',
    category: 'IT Ops & Security',
    icon: '🚨',
    accent: '#E0A40C',
    url: 'https://ai.arttechgroup.com:7777/incident-triage/',
    tag: 'Operations',
    rating: 4.7,
    short: 'Detect, root-cause and suggest resolutions for production incidents end-to-end.',
    tagline: 'Detect, root-cause and resolve production incidents end-to-end — automatically.',
    tags: [{ label: 'New', type: 'green' }, { label: 'Operations', type: 'blue' }],
    whoFor: 'SRE, DevOps and platform teams who need to cut time-to-resolution and stop firefighting the same incidents.',
    whatYouGet: 'An agent that detects incidents, correlates signals into a root cause, and recommends concrete resolution steps.',
    howItWorks: 'Connect your logs, metrics and alerts — the agent triages incoming incidents, pinpoints the likely root cause and proposes fixes.',
    featureGroups: [
      { title: 'Triage', items: ['Automatic incident detection', 'Signal correlation', 'Severity & impact scoring'] },
      { title: 'Resolution', items: ['Root-cause analysis', 'Suggested remediations', 'Post-incident summaries'] },
    ],
    useCases: [
      { title: 'Faster RCA', desc: 'Surface the likely root cause in minutes instead of hours.', industry: 'SRE' },
      { title: 'Reduced downtime', desc: 'Triage and route incidents the moment they appear.', industry: 'DevOps' },
      { title: 'Post-mortems', desc: 'Generate clear incident timelines and summaries automatically.', industry: 'Platform' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'SRE & DevOps'],
      ['Complexity', 'Medium'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'KYC / KYB Client Onboarding Agent',
    slug: 'kyc-kyb-onboarding',
    category: 'Financial Services',
    icon: '🪪',
    accent: '#F5C010',
    url: 'https://ai.arttechgroup.com:7777/kyc-kyb-onboarding/kyc',
    tag: 'Compliance',
    rating: 4.7,
    short: 'Screen, verify and onboard new clients.',
    tagline: 'Screen, verify and onboard new clients with automated KYC and KYB checks.',
    tags: [{ label: 'New', type: 'green' }, { label: 'Compliance', type: 'blue' }],
    whoFor: 'Compliance, onboarding and risk teams who need to verify clients quickly without cutting corners on due diligence.',
    whatYouGet: 'An agent that screens individuals and businesses, runs verification checks and guides clients through onboarding.',
    howItWorks: 'Connect your verification and screening sources — the agent collects documents, runs KYC/KYB checks and flags risks for review.',
    featureGroups: [
      { title: 'Verification', items: ['Identity (KYC) checks', 'Business (KYB) checks', 'Document collection'] },
      { title: 'Screening', items: ['Sanctions & watchlist screening', 'Risk scoring', 'Audit-ready records'] },
    ],
    useCases: [
      { title: 'Faster onboarding', desc: 'Take new clients from application to approved in less time.', industry: 'Fintech' },
      { title: 'Risk screening', desc: 'Catch sanctioned or high-risk entities before they onboard.', industry: 'Compliance' },
      { title: 'Audit readiness', desc: 'Keep verifiable, audit-ready records for every client.', industry: 'Risk' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'Compliance & Onboarding'],
      ['Complexity', 'Medium'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'Reconciliation Agent',
    slug: 'reconciliation-agent',
    category: 'Financial Services',
    icon: '⚖️',
    accent: '#C8920A',
    url: 'https://reconciliation-agent-arttechgroup.pages.dev/',
    tag: 'Finance',
    rating: 4.6,
    short: 'Detect, explain and clear unreconciled days.',
    tagline: 'Detect, explain and clear unreconciled days across your financial records.',
    tags: [{ label: 'New', type: 'green' }, { label: 'Finance', type: 'blue' }],
    whoFor: 'Finance and operations teams who spend hours chasing breaks and want reconciliation to clear itself.',
    whatYouGet: 'An agent that finds unreconciled days, explains the discrepancies and proposes the entries needed to clear them.',
    howItWorks: 'Connect your ledgers and statements — the agent matches transactions, isolates breaks and explains how to clear each one.',
    featureGroups: [
      { title: 'Detection', items: ['Automated matching', 'Break identification', 'Unreconciled-day alerts'] },
      { title: 'Resolution', items: ['Discrepancy explanations', 'Suggested adjustments', 'Clearing audit trail'] },
    ],
    useCases: [
      { title: 'Clear breaks faster', desc: 'Resolve unreconciled days in minutes, not hours.', industry: 'Finance' },
      { title: 'Explain discrepancies', desc: 'Understand exactly why a day failed to reconcile.', industry: 'Operations' },
      { title: 'Month-end close', desc: 'Walk into close with a clean, explained reconciliation.', industry: 'Accounting' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'Finance Ops'],
      ['Complexity', 'Medium'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'Fraud Detection Agent',
    slug: 'fraud-detection',
    category: 'Financial Services',
    icon: '🛑',
    accent: '#EAB308',
    url: '',
    tag: 'Risk',
    rating: 4.8,
    short: 'Detect, flag and block fraudulent transactions.',
    tagline: 'Detect, flag and block fraudulent transactions in real time.',
    tags: [{ label: 'New', type: 'green' }, { label: 'Risk', type: 'blue' }],
    whoFor: 'Risk, payments and fraud teams who need to stop fraudulent transactions before they settle.',
    whatYouGet: 'An agent that scores transactions for fraud, flags suspicious activity and blocks high-risk payments automatically.',
    howItWorks: 'Connect your transaction stream — the agent scores each payment in real time, flags anomalies and blocks high-risk transactions.',
    featureGroups: [
      { title: 'Detection', items: ['Real-time transaction scoring', 'Anomaly detection', 'Behavioral patterns'] },
      { title: 'Response', items: ['Automatic blocking', 'Risk-based flagging', 'Case audit trail'] },
    ],
    useCases: [
      { title: 'Stop fraud early', desc: 'Block high-risk transactions before they settle.', industry: 'Payments' },
      { title: 'Reduce false positives', desc: 'Flag genuine threats without blocking good customers.', industry: 'Risk' },
      { title: 'Investigation support', desc: 'Give analysts a clear audit trail for every flagged case.', industry: 'Fraud' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'Risk & Payments'],
      ['Complexity', 'Medium'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'Customer Support Sentiment & Insight Analyzer',
    slug: 'support-sentiment-analyzer',
    category: 'Customer Service',
    icon: '🎧',
    accent: '#F5C010',
    url: '',
    tag: 'Analytics',
    rating: 4.7,
    short: 'Turn support conversations into instant, actionable insights.',
    tagline: 'Analyze support conversations and turn them into clear, actionable insights in seconds.',
    tags: [{ label: 'New', type: 'green' }, { label: 'Analytics', type: 'blue' }],
    whoFor: 'Support and CX teams who need to understand why customers reach out, how they feel and what to do next.',
    whatYouGet: 'An agent that reads support conversations and surfaces intent, sentiment, urgency and recommended next actions.',
    howItWorks: 'Feed in support conversations — the agent classifies intent, gauges sentiment and urgency, and suggests next steps instantly.',
    featureGroups: [
      { title: 'Understanding', items: ['Intent detection', 'Sentiment analysis', 'Urgency scoring'] },
      { title: 'Action', items: ['Recommended next steps', 'Trend insights', 'Escalation flags'] },
    ],
    useCases: [
      { title: 'Faster triage', desc: 'Spot urgent, unhappy customers the moment they write in.', industry: 'Support' },
      { title: 'Voice-of-customer', desc: 'Understand why customers contact you and how they feel.', industry: 'CX' },
      { title: 'Coaching insights', desc: 'Turn conversations into clear actions for the team.', industry: 'Operations' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'Support & CX'],
      ['Complexity', 'Low'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'AI HR Hiring Manager',
    slug: 'hr-hiring-manager',
    category: 'HR',
    icon: '🧑‍💼',
    accent: '#FBD75B',
    url: '',
    tag: 'Agent',
    rating: 4.6,
    short: 'Automate hiring — from job descriptions to resume scoring.',
    tagline: 'Automate recruitment with standardized, unbiased hiring from job description to candidate evaluation.',
    tags: [{ label: 'New', type: 'green' }, { label: 'Agent', type: 'blue' }],
    whoFor: 'Recruiters and hiring managers who want a consistent, objective process across every role.',
    whatYouGet: 'An agent that generates job descriptions, defines evaluation criteria and scores resumes objectively.',
    howItWorks: 'Describe the role — the agent drafts the job description, sets evaluation criteria and ranks candidate resumes against them.',
    featureGroups: [
      { title: 'Define', items: ['Job description generation', 'Evaluation criteria', 'Role calibration'] },
      { title: 'Evaluate', items: ['Objective resume scoring', 'Candidate ranking', 'Bias reduction'] },
    ],
    useCases: [
      { title: 'Faster shortlisting', desc: 'Score and rank candidates against clear criteria.', industry: 'Recruiting' },
      { title: 'Consistent hiring', desc: 'Standardize evaluation across roles and reviewers.', industry: 'HR' },
      { title: 'Fairer decisions', desc: 'Reduce bias with objective, criteria-based scoring.', industry: 'People Ops' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'HR & Recruiting'],
      ['Complexity', 'Low'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'Sales Enablement Content Generator',
    slug: 'sales-enablement-generator',
    category: 'Sales',
    icon: '📣',
    accent: '#E0A40C',
    url: '',
    tag: 'Generative',
    rating: 4.5,
    short: 'Generate tailored, on-brand B2B sales content fast.',
    tagline: 'Create tailored, consistent sales enablement assets for B2B teams in minutes.',
    tags: [{ label: 'New', type: 'green' }, { label: 'Generative', type: 'blue' }],
    whoFor: 'B2B sales and enablement teams who need consistent, high-quality, ready-to-use content.',
    whatYouGet: 'A generator that produces tailored sales enablement materials with consistent messaging.',
    howItWorks: 'Describe your audience and offer — the generator builds tailored, on-brand enablement assets ready to use.',
    featureGroups: [
      { title: 'Generation', items: ['Tailored content', 'Consistent messaging', 'Reusable assets'] },
      { title: 'Enablement', items: ['Pitch & battlecard support', 'Brand alignment', 'Team-ready output'] },
    ],
    useCases: [
      { title: 'Sales collateral', desc: 'Spin up tailored decks, one-pagers and battlecards.', industry: 'Sales' },
      { title: 'Message consistency', desc: 'Keep every asset on-brand and aligned.', industry: 'Marketing' },
      { title: 'Faster enablement', desc: 'Equip reps with ready-to-use content quickly.', industry: 'Enablement' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'B2B Sales'],
      ['Complexity', 'Low'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'HR Policy Generator',
    slug: 'hr-policy-generator',
    category: 'HR',
    icon: '📄',
    accent: '#C8920A',
    url: '',
    tag: 'Generative',
    rating: 4.6,
    short: 'Create compliant, ready-to-use HR policies.',
    tagline: 'Generate compliant, professional HR policies ready for implementation.',
    tags: [{ label: 'New', type: 'green' }, { label: 'Generative', type: 'blue' }],
    whoFor: 'HR and compliance teams who need policies that meet labor laws without the manual drafting.',
    whatYouGet: 'A generator that gathers requirements, validates compliance and produces ready-to-use policy documents.',
    howItWorks: 'Answer a few guided questions — the agent validates against labor laws and produces a professional, ready-to-use policy.',
    featureGroups: [
      { title: 'Requirements', items: ['Guided requirements gathering', 'Jurisdiction selection', 'Scope definition'] },
      { title: 'Compliance', items: ['Labor-law validation', 'Professional formatting', 'Implementation-ready docs'] },
    ],
    useCases: [
      { title: 'Policy drafting', desc: 'Produce professional HR policies in minutes.', industry: 'HR' },
      { title: 'Compliance checks', desc: 'Validate policies against labor laws and regulations.', industry: 'Compliance' },
      { title: 'Standardization', desc: 'Keep policies consistent and implementation-ready.', industry: 'People Ops' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'HR & Compliance'],
      ['Complexity', 'Low'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'RFP & Proposal Response Automation',
    slug: 'rfp-proposal-automation',
    category: 'Sales',
    icon: '📑',
    accent: '#EAB308',
    url: '',
    tag: 'Automation',
    rating: 4.7,
    short: 'Draft structured RFP and proposal responses automatically.',
    tagline: 'Analyze RFPs and generate structured proposal drafts — faster and more consistent.',
    tags: [{ label: 'New', type: 'green' }, { label: 'Automation', type: 'blue' }],
    whoFor: 'Sales, bid and compliance teams responding to enterprise RFPs under tight deadlines.',
    whatYouGet: 'An agent that analyzes RFP documents and generates structured, consistent proposal drafts.',
    howItWorks: 'Upload an RFP — the agent analyzes requirements, drafts a structured response and keeps sales and compliance aligned.',
    featureGroups: [
      { title: 'Analysis', items: ['RFP document parsing', 'Requirement extraction', 'Gap identification'] },
      { title: 'Response', items: ['Structured proposal drafts', 'Consistent messaging', 'Team collaboration'] },
    ],
    useCases: [
      { title: 'Faster responses', desc: 'Cut RFP turnaround with auto-generated drafts.', industry: 'Sales' },
      { title: 'Consistent proposals', desc: 'Keep messaging aligned across every response.', industry: 'Bid Management' },
      { title: 'Team alignment', desc: 'Coordinate sales and compliance on one draft.', industry: 'Compliance' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'Sales & Compliance'],
      ['Complexity', 'Medium'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'IT Helpdesk Agent',
    slug: 'it-helpdesk-agent',
    category: 'IT Ops & Security',
    icon: '🖥️',
    accent: '#D9A41A',
    url: '',
    tag: 'Agent',
    rating: 4.6,
    short: 'Instant IT support, troubleshooting and ticketing.',
    tagline: 'Automate employee IT support with instant answers, guided troubleshooting and auto ticketing.',
    tags: [{ label: 'New', type: 'green' }, { label: 'Agent', type: 'blue' }],
    whoFor: 'IT and support teams who want to deflect common tickets and speed up incident management.',
    whatYouGet: 'An agent that answers IT questions, guides troubleshooting and creates tickets automatically.',
    howItWorks: 'Employees ask in plain language — the agent answers, walks through fixes and opens tickets in your IT systems when needed.',
    featureGroups: [
      { title: 'Self-service', items: ['Instant IT answers', 'Guided troubleshooting', 'Knowledge lookups'] },
      { title: 'Incidents', items: ['Automated ticket creation', 'IT system integration', 'Incident routing'] },
    ],
    useCases: [
      { title: 'Ticket deflection', desc: 'Resolve common IT questions without an agent.', industry: 'IT' },
      { title: 'Guided fixes', desc: 'Walk employees through troubleshooting steps.', industry: 'Support' },
      { title: 'Faster incidents', desc: 'Auto-create and route tickets to the right team.', industry: 'IT Operations' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'IT & Support'],
      ['Complexity', 'Medium'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'Anti-Glaze Expert',
    slug: 'anti-glaze-expert',
    category: 'Research & Analysis',
    icon: '🪞',
    accent: '#F5C010',
    url: '',
    tag: 'Expert',
    rating: 4.7,
    short: 'Blunt, no-flattery expert answers with explicit confidence levels.',
    tagline: 'A brutally honest expert that drops the flattery, leads with counterarguments and tells you how sure it is.',
    tags: [{ label: 'New', type: 'green' }, { label: 'Expert', type: 'blue' }],
    whoFor: 'Anyone who wants straight answers — founders, analysts and decision-makers tired of hedging and validation.',
    whatYouGet: 'A direct expert consultation that challenges weak premises, leads with the strongest counterargument and states its confidence.',
    howItWorks: 'Ask about any topic — the agent answers completely and directly, holds its position under pushback, and flags how certain it is.',
    featureGroups: [
      { title: 'Honesty', items: ['No flattery or hedging', 'Leads with counterarguments', 'Holds position under pushback'] },
      { title: 'Clarity', items: ['Explicit confidence levels', 'Complete, detailed answers', 'Calls out weak premises'] },
    ],
    useCases: [
      { title: 'Pressure-test ideas', desc: 'Get the strongest case against your plan before you commit.', industry: 'Strategy' },
      { title: 'Honest reviews', desc: 'Hear what is actually wrong, not what sounds nice.', industry: 'Product' },
      { title: 'Decision support', desc: 'Weigh options with clear confidence on each.', industry: 'Leadership' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'General'],
      ['Complexity', 'Low'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'Prompt Builder',
    slug: 'goal-prompt-builder',
    category: 'Developer Tools',
    icon: '🛠️',
    accent: '#FBD75B',
    url: '',
    tag: 'Developer',
    rating: 4.6,
    short: 'Turn a vague idea into a complete autonomous coding prompt.',
    tagline: 'Interviews you about what to build and generates a complete /goal prompt a coding agent can run end-to-end.',
    tags: [{ label: 'New', type: 'green' }, { label: 'Developer', type: 'blue' }],
    whoFor: 'Developers who want coding agents to run autonomously instead of babysitting vague tasks.',
    whatYouGet: 'A guided interview that extracts the full context a coding agent needs and produces a ready-to-run /goal prompt.',
    howItWorks: 'Answer a few questions about your goal — the builder gathers context and writes a complete /goal prompt for Claude Code.',
    featureGroups: [
      { title: 'Intake', items: ['Guided requirement interview', 'Context extraction', 'Scope & constraints capture'] },
      { title: 'Output', items: ['Complete /goal prompt', 'Autonomous-ready instructions', 'Copy-paste into Claude Code'] },
    ],
    useCases: [
      { title: 'Autonomous builds', desc: 'Hand a coding agent a task it can finish without check-ins.', industry: 'Engineering' },
      { title: 'Faster scoping', desc: 'Turn fuzzy ideas into precise, actionable specs.', industry: 'Product' },
      { title: 'Consistent prompts', desc: 'Standardize how tasks are handed to AI agents.', industry: 'DevTools' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'Developers'],
      ['Complexity', 'Low'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'Credit & Debit Card Dispute Resolution',
    slug: 'card-dispute-resolution',
    category: 'Financial Services',
    icon: '💳',
    accent: '#E0A40C',
    url: '',
    tag: 'Finance',
    rating: 4.6,
    short: 'Automate card dispute intake, verification and resolution.',
    tagline: 'A multi-agent system that handles credit and debit card disputes end-to-end while staying compliant.',
    tags: [{ label: 'New', type: 'green' }, { label: 'Finance', type: 'blue' }],
    whoFor: 'Card, payments and risk teams handling charge disputes who need speed without losing compliance.',
    whatYouGet: 'An end-to-end workflow that identifies, verifies and resolves disputes while keeping an auditable trail.',
    howItWorks: 'Disputes are taken in and verified automatically, routed through resolution steps, and tracked to a compliant outcome.',
    featureGroups: [
      { title: 'Handling', items: ['Automated intake', 'Identity & claim verification', 'Guided resolution'] },
      { title: 'Assurance', items: ['Compliance checks', 'Audit trail', 'Customer updates'] },
    ],
    useCases: [
      { title: 'Faster resolution', desc: 'Move disputes from intake to outcome with less manual work.', industry: 'Payments' },
      { title: 'Stay compliant', desc: 'Keep every step verifiable and within the rules.', industry: 'Risk' },
      { title: 'Better experience', desc: 'Keep customers informed throughout the dispute.', industry: 'Banking' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'Payments & Risk'],
      ['Complexity', 'Medium'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'Brand Compliance & Governance Agent',
    slug: 'brand-compliance-governance',
    category: 'Legal & Compliance',
    icon: '🏷️',
    accent: '#C8920A',
    url: '',
    tag: 'Compliance',
    rating: 4.6,
    short: 'Check content against brand guidelines and flag risks.',
    tagline: 'Reviews content against your brand guidelines, flags risks, suggests rewrites and reports on consistency.',
    tags: [{ label: 'New', type: 'green' }, { label: 'Compliance', type: 'blue' }],
    whoFor: 'Brand, marketing and compliance teams keeping content on-brand and on-message across channels.',
    whatYouGet: 'Automated review of content against brand guidelines, with risk flags, suggested rewrites and reports.',
    howItWorks: 'Submit content — the agent checks it against your guidelines, flags issues, suggests fixes and reports findings.',
    featureGroups: [
      { title: 'Review', items: ['Guideline checks', 'Risk flagging', 'Multi-format content'] },
      { title: 'Action', items: ['Suggested rewrites', 'Consistency reports', 'Channel coverage'] },
    ],
    useCases: [
      { title: 'On-brand content', desc: 'Keep every asset aligned with brand guidelines.', industry: 'Marketing' },
      { title: 'Risk flagging', desc: 'Catch compliance issues before content ships.', industry: 'Brand' },
      { title: 'Governance', desc: 'Report on brand consistency across channels.', industry: 'Governance' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'Brand & Marketing'],
      ['Complexity', 'Medium'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'Legal Contract Clause Analyzer',
    slug: 'legal-contract-analyzer',
    category: 'Legal & Compliance',
    icon: '📜',
    accent: '#EAB308',
    url: '',
    tag: 'Legal',
    rating: 4.7,
    short: 'Extract clauses, surface risks and track obligations.',
    tagline: 'A multi-agent system that extracts clauses, identifies risks and tracks obligations across long contracts.',
    tags: [{ label: 'New', type: 'green' }, { label: 'Legal', type: 'blue' }],
    whoFor: 'Legal, procurement and deal teams reviewing contracts who need risks and obligations surfaced fast.',
    whatYouGet: 'Specialized agents that extract clauses, flag risks against market standards and produce actionable summaries.',
    howItWorks: 'Upload a contract — agents extract clauses, compare against standards, flag risks and track obligations.',
    featureGroups: [
      { title: 'Analysis', items: ['Clause extraction', 'Risk identification', 'Market-standard comparison'] },
      { title: 'Tracking', items: ['Obligation tracking', 'Actionable summaries', 'Multi-page coverage'] },
    ],
    useCases: [
      { title: 'Vendor review', desc: 'Spot risky clauses in vendor and SaaS agreements.', industry: 'Legal' },
      { title: 'Due diligence', desc: 'Speed up M&A contract review.', industry: 'M&A' },
      { title: 'Obligation tracking', desc: 'Capture commitments scattered across the contract.', industry: 'Operations' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'Legal'],
      ['Complexity', 'Medium'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'Universal Banking Customer Support Agent',
    slug: 'universal-banking-support',
    category: 'Customer Service',
    icon: '🏦',
    accent: '#D9A41A',
    url: '',
    tag: 'Banking',
    rating: 4.7,
    short: 'Route banking queries to specialized support sub-agents.',
    tagline: 'A chat assistant that routes banking queries to specialized sub-agents while keeping one conversation context.',
    tags: [{ label: 'New', type: 'green' }, { label: 'Banking', type: 'blue' }],
    whoFor: 'Banks and fintechs that want one assistant to cover accounts, loans, cards, disputes and more.',
    whatYouGet: 'A universal agent that orchestrates 12 specialized sub-agents, keeps context and switches domains seamlessly.',
    howItWorks: 'Customers chat in one place — the universal agent routes each query to the right sub-agent and keeps context.',
    featureGroups: [
      { title: 'Orchestration', items: ['Intelligent query routing', '12 specialized sub-agents', 'Context retention'] },
      { title: 'Coverage', items: ['Accounts & loans', 'Cards & disputes', 'Seamless domain switching'] },
    ],
    useCases: [
      { title: 'Unified support', desc: 'One chat covers every banking domain.', industry: 'Banking' },
      { title: 'Accurate answers', desc: 'Sub-agents pull the right data per domain.', industry: 'Fintech' },
      { title: 'Context retention', desc: 'Keep the thread as topics change.', industry: 'Support' },
    ],
    specs: [
      ['Deployment', 'Web / Embed'], ['Availability', 'Cloud'], ['Audience', 'Banking'],
      ['Complexity', 'Medium'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'Procurement Document Generator (RFP/RFQ)',
    slug: 'procurement-doc-generator',
    category: 'Sales',
    icon: '🧾',
    accent: '#F5C010',
    url: '',
    tag: 'Procurement',
    rating: 4.5,
    short: 'Generate RFP/RFQ documents from your requirements.',
    tagline: 'Creates RFP and RFQ procurement documents tailored to your requirements in minutes.',
    tags: [{ label: 'New', type: 'green' }, { label: 'Procurement', type: 'blue' }],
    whoFor: 'Procurement and operations teams who need consistent RFP/RFQ documents without starting from scratch.',
    whatYouGet: 'A generator that turns your requirements into structured RFP or RFQ documents ready to send.',
    howItWorks: 'Describe your requirement — the generator drafts a structured RFP or RFQ document for procurement.',
    featureGroups: [
      { title: 'Generation', items: ['RFP & RFQ documents', 'Requirement-driven', 'Structured output'] },
      { title: 'Efficiency', items: ['Reusable templates', 'Consistent format', 'Faster sourcing'] },
    ],
    useCases: [
      { title: 'Faster sourcing', desc: 'Draft procurement docs in minutes, not days.', industry: 'Procurement' },
      { title: 'Consistency', desc: 'Keep every RFP/RFQ in a standard format.', industry: 'Operations' },
      { title: 'Requirement capture', desc: 'Turn needs into a complete document.', industry: 'Sourcing' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'Procurement'],
      ['Complexity', 'Low'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'Customer Support Resolution Intelligence Orchestrator',
    slug: 'support-resolution-orchestrator',
    category: 'Customer Service',
    icon: '🧭',
    accent: '#FBD75B',
    url: '',
    tag: 'Support',
    rating: 4.6,
    short: 'Tell whether support issues were truly resolved.',
    tagline: 'Analyzes support conversations to judge real resolution, surface hidden risks and recommend next best actions.',
    tags: [{ label: 'New', type: 'green' }, { label: 'Support', type: 'blue' }],
    whoFor: 'Support leaders who want to catch unresolved issues and escalation risks before they blow up.',
    whatYouGet: 'Analysis that determines whether issues were really resolved, flags risks and recommends next actions.',
    howItWorks: 'Feed in support conversations — the orchestrator judges resolution, surfaces risks and suggests next steps.',
    featureGroups: [
      { title: 'Insight', items: ['Resolution detection', 'Hidden-risk surfacing', 'Escalation signals'] },
      { title: 'Action', items: ['Next-best-action', 'Pre-escalation alerts', 'Quality signals'] },
    ],
    useCases: [
      { title: 'Catch non-resolutions', desc: 'Find issues that look closed but are not.', industry: 'Support' },
      { title: 'Reduce escalations', desc: 'Act on risks before they escalate.', industry: 'CX' },
      { title: 'Coaching', desc: 'Spot where conversations went wrong.', industry: 'Operations' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'Support & CX'],
      ['Complexity', 'Medium'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'Conversation Summary & Action Tracker',
    slug: 'conversation-summary-tracker',
    category: 'Customer Service',
    icon: '📝',
    accent: '#E0A40C',
    url: '',
    tag: 'Support',
    rating: 4.6,
    short: 'Summarize support chats and capture action items.',
    tagline: 'Turns call and chat transcripts into factual summaries, action items and a reliable record of every interaction.',
    tags: [{ label: 'New', type: 'green' }, { label: 'Support', type: 'blue' }],
    whoFor: 'Support teams who want to drop manual note-taking and keep consistent records at scale.',
    whatYouGet: 'Concise summaries, extracted action items, captured concerns and recorded agent commitments — automatically.',
    howItWorks: 'Feed in call or chat transcripts — the agent summarizes, extracts actions and records commitments.',
    featureGroups: [
      { title: 'Summaries', items: ['Factual recaps', 'Customer concerns', 'Agent commitments'] },
      { title: 'Tracking', items: ['Action item extraction', 'Consistent records', 'System of record'] },
    ],
    useCases: [
      { title: 'No more notes', desc: 'Eliminate manual after-call note-taking.', industry: 'Support' },
      { title: 'Action tracking', desc: 'Never lose a follow-up commitment.', industry: 'CX' },
      { title: 'Record of truth', desc: 'Keep a reliable log of every interaction.', industry: 'Operations' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'Support & CX'],
      ['Complexity', 'Low'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'Regulatory Compliance Assessment System',
    slug: 'regulatory-compliance-assessment',
    category: 'Legal & Compliance',
    icon: '📋',
    accent: '#C8920A',
    url: '',
    tag: 'Compliance',
    rating: 4.7,
    short: 'Assess compliance gaps and produce action plans.',
    tagline: 'A multi-agent system that finds applicable regulations, assesses gaps and generates prioritized action plans.',
    tags: [{ label: 'New', type: 'green' }, { label: 'Compliance', type: 'blue' }],
    whoFor: 'Compliance and risk teams keeping policies and processes aligned with evolving regulations.',
    whatYouGet: 'Agents that identify applicable regulations, assess gaps against current requirements and prioritize actions.',
    howItWorks: 'Submit policies or processes — agents map regulations, assess gaps and produce a prioritized action plan.',
    featureGroups: [
      { title: 'Assessment', items: ['Applicable-regulation mapping', 'Gap analysis', 'Current-requirement research'] },
      { title: 'Output', items: ['Prioritized action plans', 'Pre-audit prep', 'Policy gap reports'] },
    ],
    useCases: [
      { title: 'Privacy compliance', desc: 'Assess against GDPR and CCPA.', industry: 'Privacy' },
      { title: 'Financial rules', desc: 'Check SOX and PCI-DSS posture.', industry: 'Finance' },
      { title: 'Pre-audit prep', desc: 'Close gaps before the auditors arrive.', industry: 'Risk' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'Compliance & Risk'],
      ['Complexity', 'Medium'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'Goal-Driven Autonomous Agent',
    slug: 'goal-driven-autonomous-agent',
    category: 'Developer Tools',
    icon: '🎯',
    accent: '#EAB308',
    url: '',
    tag: 'Automation',
    rating: 4.6,
    short: 'Loops plan-execute-evaluate until the goal is met.',
    tagline: 'Give it a task and a goal condition and it keeps looping — plan, execute, evaluate — until the goal is fully met.',
    tags: [{ label: 'New', type: 'green' }, { label: 'Automation', type: 'blue' }],
    whoFor: 'Builders who want agents that finish the job instead of stopping at the first obstacle.',
    whatYouGet: 'A supervisor orchestrating planner, executor and evaluator agents in a loop until your goal condition is met.',
    howItWorks: 'Set a task and goal condition — a planner, executor and evaluator loop until the evaluator confirms it is met.',
    featureGroups: [
      { title: 'Loop', items: ['Planner breaks down work', 'Executor does the work', 'Evaluator checks the goal'] },
      { title: 'Autonomy', items: ['Continuous looping', 'Goal-condition driven', 'Supervisor orchestration'] },
    ],
    useCases: [
      { title: 'Finish the job', desc: 'Keep working until the goal is actually met.', industry: 'Automation' },
      { title: 'Complex tasks', desc: 'Break down and execute multi-step work.', industry: 'Engineering' },
      { title: 'Hands-off runs', desc: 'Let agents loop without babysitting.', industry: 'Operations' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'Developers'],
      ['Complexity', 'Medium'], ['Pricing', 'Contact sales'],
    ],
  },
]
