// Rich per-agent data, modelled on an agent-directory detail page.
export const AGENTS = [
  {
    name: 'HR Agent',
    icon: '👥',
    accent: '#6b78b8',
    url: 'https://ai.arttechgroup.com:7777/hr-agent/',
    tag: 'Agent',
    rating: 4.6,
    short: 'Automate hiring and everyday HR workflows in plain English.',
    tagline: 'Automate hiring and HR operations with an AI agent that understands plain English.',
    tags: [{ label: 'Featured', type: 'green' }, { label: 'Agent', type: 'blue' }],
    whoFor: 'HR teams, recruiters and people-ops leaders who want to cut manual work and respond to employees faster.',
    whatYouGet: 'An always-on assistant that screens candidates, answers employee questions, and handles onboarding and policy lookups.',
    howItWorks: 'Connect your HR data and job posts, then simply ask in natural language — the agent screens, drafts and answers using your own policies.',
    featureGroups: [
      { title: 'Recruiting', items: ['Automated candidate screening', 'Resume ranking & shortlisting', 'Interview scheduling support'] },
      { title: 'Employee Support', items: ['24/7 policy Q&A', 'Guided onboarding', 'Leave & benefits lookups'] },
    ],
    useCases: [
      { title: 'Faster candidate screening', desc: 'Shortlist the best applicants from hundreds of resumes in minutes.', industry: 'Recruiting' },
      { title: 'Employee self-service', desc: 'Staff get instant, accurate answers to HR questions any time.', industry: 'People Ops' },
      { title: 'Streamlined onboarding', desc: 'Walk new hires through paperwork, policies and first-week tasks.', industry: 'HR' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'HR & Recruiting'],
      ['Complexity', 'Low'], ['Pricing', 'Free option'],
    ],
  },
  {
    name: 'Cold Email Generator',
    icon: '✉️',
    accent: '#8a7bb0',
    url: 'https://ai.arttechgroup.com:7777/coldemail/',
    tag: 'Generative',
    rating: 4.5,
    short: 'Generate personalized, high-converting outreach at scale.',
    tagline: 'Write personalized, high-converting cold emails in seconds — at scale.',
    tags: [{ label: 'New', type: 'green' }, { label: 'Generative', type: 'blue' }],
    whoFor: 'Sales, growth and founders who need consistent, personalized outreach without spending hours writing.',
    whatYouGet: 'A generator that crafts tailored emails, controls tone and templates, and builds smart follow-up sequences.',
    howItWorks: 'Paste a prospect or list and describe your offer — the agent drafts personalized emails and ready-to-send sequences.',
    featureGroups: [
      { title: 'Generation', items: ['Personalized at scale', 'Tone & style control', 'Reusable templates'] },
      { title: 'Outreach', items: ['Multi-step follow-ups', 'Subject-line variants', 'A/B-ready copy'] },
    ],
    useCases: [
      { title: 'Outbound campaigns', desc: 'Spin up a personalized campaign for a whole prospect list.', industry: 'Sales' },
      { title: 'Founder outreach', desc: 'Reach investors and partners with sharp, tailored emails.', industry: 'Startups' },
      { title: 'Re-engagement', desc: 'Win back cold leads with relevant follow-up sequences.', industry: 'Growth' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'Sales & Growth'],
      ['Complexity', 'Low'], ['Pricing', 'Free option'],
    ],
  },
  {
    name: 'Fintech Chatbot',
    icon: '💬',
    accent: '#5b86a8',
    url: 'https://ai.arttechgroup.com:7777/chatbot/',
    tag: 'Chatbot',
    rating: 4.7,
    short: 'Secure conversational AI built for fintech support.',
    tagline: 'A secure, always-on conversational assistant purpose-built for fintech.',
    tags: [{ label: 'Live', type: 'green' }, { label: 'Chatbot', type: 'blue' }],
    whoFor: 'Fintech and banking teams that need compliant, 24/7 customer support that can handle sensitive queries.',
    whatYouGet: 'A conversational assistant that answers customer questions, handles transactions and resolves multi-intent conversations.',
    howItWorks: 'Connect your product knowledge and policies — the bot responds securely, escalating to humans when needed.',
    featureGroups: [
      { title: 'Conversations', items: ['24/7 customer support', 'Multi-intent handling', 'Human handoff'] },
      { title: 'Security', items: ['Secure transaction queries', 'Compliance-aware replies', 'Audit logging'] },
    ],
    useCases: [
      { title: 'Customer support', desc: 'Resolve common queries instantly, reducing ticket volume.', industry: 'Fintech' },
      { title: 'Transaction help', desc: 'Guide users through payments, transfers and statements.', industry: 'Banking' },
      { title: 'Onboarding & KYC', desc: 'Answer onboarding questions and walk users through steps.', industry: 'Finance' },
    ],
    specs: [
      ['Deployment', 'Web / Embed'], ['Availability', 'Cloud'], ['Audience', 'Fintech'],
      ['Complexity', 'Medium'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'Unified Chatbot',
    icon: '🤖',
    accent: '#4f8f96',
    url: 'https://ai.arttechgroup.com:7777/unified-chat',
    tag: 'Chatbot',
    rating: 4.6,
    short: 'One intelligent assistant across all of your channels.',
    tagline: 'Bring every conversation into one intelligent, context-aware assistant.',
    tags: [{ label: 'Featured', type: 'green' }, { label: 'Chatbot', type: 'blue' }],
    whoFor: 'Teams running support across multiple channels who want one consistent assistant and knowledge base.',
    whatYouGet: 'A single assistant that works across channels, shares one knowledge base, and keeps context everywhere.',
    howItWorks: 'Connect your channels and knowledge sources — the assistant serves consistent answers across all of them.',
    featureGroups: [
      { title: 'Omnichannel', items: ['One bot, every channel', 'Consistent answers', 'Context carries over'] },
      { title: 'Knowledge', items: ['Shared knowledge base', 'Live source sync', 'Smart routing'] },
    ],
    useCases: [
      { title: 'Unified support', desc: 'Answer customers the same way on web, chat and more.', industry: 'Support' },
      { title: 'Internal helpdesk', desc: 'Give employees one place to ask anything.', industry: 'Operations' },
      { title: 'Knowledge hub', desc: 'Turn scattered docs into instant answers.', industry: 'Enterprise' },
    ],
    specs: [
      ['Deployment', 'Web / Embed'], ['Availability', 'Cloud'], ['Audience', 'Enterprise'],
      ['Complexity', 'Medium'], ['Pricing', 'Free option'],
    ],
  },
  {
    name: 'Art Intelligence Platform',
    icon: '📊',
    accent: '#a8916a',
    url: 'https://ai.arttechgroup.com:7777/art-intelligence/dashboard',
    tag: 'Platform',
    rating: 4.8,
    short: 'Turn enterprise data into decisions with live analytics.',
    tagline: 'Turn raw enterprise data into decisions with real-time analytics and insights.',
    tags: [{ label: 'Featured', type: 'green' }, { label: 'Platform', type: 'blue' }],
    whoFor: 'Leaders and analysts who need a single, real-time view of their data to make faster decisions.',
    whatYouGet: 'A platform with real-time analytics, customizable dashboards and actionable, AI-generated insights.',
    howItWorks: 'Connect your data sources and build dashboards — the platform surfaces trends and insights automatically.',
    featureGroups: [
      { title: 'Analytics', items: ['Real-time metrics', 'Custom dashboards', 'Drill-down views'] },
      { title: 'Intelligence', items: ['AI-generated insights', 'Anomaly detection', 'Forecasting'] },
    ],
    useCases: [
      { title: 'Executive dashboards', desc: 'Give leadership a live view of the business.', industry: 'Enterprise' },
      { title: 'Operational reporting', desc: 'Replace manual reports with automated dashboards.', industry: 'Operations' },
      { title: 'Decision support', desc: 'Spot trends and act before they become problems.', industry: 'Strategy' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'Enterprise'],
      ['Complexity', 'Medium'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'FintechOps',
    icon: '⚙️',
    accent: '#5f9080',
    url: 'https://fintechops-arttechgroup.pages.dev/',
    tag: 'Operations',
    rating: 4.5,
    short: 'Automate and orchestrate your financial operations.',
    tagline: 'Streamline and orchestrate financial operations end-to-end.',
    tags: [{ label: 'Live', type: 'green' }, { label: 'Operations', type: 'blue' }],
    whoFor: 'Finance and operations teams that want to automate manual processes and monitor them in one place.',
    whatYouGet: 'Workflow automation, reconciliation and live operations monitoring across your financial processes.',
    howItWorks: 'Define your workflows and connect systems — FintechOps automates steps and flags exceptions in real time.',
    featureGroups: [
      { title: 'Automation', items: ['Workflow automation', 'Automated reconciliation', 'Exception handling'] },
      { title: 'Monitoring', items: ['Live ops dashboards', 'Alerts & SLAs', 'Audit trail'] },
    ],
    useCases: [
      { title: 'Reconciliation', desc: 'Match transactions automatically and surface mismatches.', industry: 'Finance' },
      { title: 'Process automation', desc: 'Remove repetitive manual steps from operations.', industry: 'Operations' },
      { title: 'Ops monitoring', desc: 'Track financial workflows live and catch issues early.', industry: 'Fintech' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'Finance Ops'],
      ['Complexity', 'Medium'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'Scheme Compliance Portal',
    icon: '🛡️',
    accent: '#6e72a6',
    url: 'https://ai.arttechgroup.com:7777/scheme-compliance-art/login',
    tag: 'Compliance',
    rating: 4.7,
    short: 'End-to-end scheme compliance management — B4B, ART edition.',
    tagline: 'End-to-end scheme compliance management — the ART edition of B4B.',
    tags: [{ label: 'Secure', type: 'green' }, { label: 'Compliance', type: 'blue' }],
    whoFor: 'Compliance and risk teams managing schemes who need to track obligations and stay audit-ready.',
    whatYouGet: 'A portal to track compliance obligations, generate audit-ready reports and stay ahead of requirements.',
    howItWorks: 'Configure your schemes and obligations — the portal tracks status, deadlines and produces reports on demand.',
    featureGroups: [
      { title: 'Compliance', items: ['Obligation tracking', 'Deadline reminders', 'Status dashboards'] },
      { title: 'Reporting', items: ['Audit-ready reports', 'Evidence management', 'Role-based access'] },
    ],
    useCases: [
      { title: 'Obligation tracking', desc: 'Keep every requirement and deadline in one place.', industry: 'Compliance' },
      { title: 'Audit readiness', desc: 'Generate audit-ready reports in a few clicks.', industry: 'Risk' },
      { title: 'Scheme management', desc: 'Manage multiple schemes with role-based control.', industry: 'Governance' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'Compliance & Risk'],
      ['Complexity', 'Medium'], ['Pricing', 'Contact sales'],
    ],
  },
]
