// Rich per-agent data, modelled on an agent-directory detail page.
export const AGENTS = [
  {
    name: 'HR Agent',
    slug: 'hr-agent',
    icon: '👥',
    accent: '#F5C010',
    url: 'https://ai.arttechgroup.com:7777/hr-agent/',
    tag: 'Agent',
    rating: 4.6,
    short: 'Automate hiring and everyday HR workflows in plain English.',
    tagline: 'Automate hiring and HR operations with an AI agent that understands plain English.',
    tags: [{ label: 'Featured', type: 'green' }, { label: 'Agent', type: 'blue' }],
    whoFor: 'HR teams, recruiters and people-ops leaders who want to cut manual work and respond to employees faster.',
    whatYouGet: 'An always-on assistant that screens candidates, answers employee questions, and handles onboarding and policy lookups.',
    howItWorks: 'Connect your HR data and job posts, then simply ask in natural language — the agent screens, drafts and answers using your own policies.',
    featureGroups: [
      { title: 'Recruiting', items: ['Automated candidate screening', 'Resume ranking & shortlisting', 'Interview scheduling support'] },
      { title: 'Employee Support', items: ['24/7 policy Q&A', 'Guided onboarding', 'Leave & benefits lookups'] },
    ],
    useCases: [
      { title: 'Faster candidate screening', desc: 'Shortlist the best applicants from hundreds of resumes in minutes.', industry: 'Recruiting' },
      { title: 'Employee self-service', desc: 'Staff get instant, accurate answers to HR questions any time.', industry: 'People Ops' },
      { title: 'Streamlined onboarding', desc: 'Walk new hires through paperwork, policies and first-week tasks.', industry: 'HR' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'HR & Recruiting'],
      ['Complexity', 'Low'], ['Pricing', 'Free option'],
    ],
  },
  {
    name: 'Cold Email Generator',
    slug: 'coldemail',
    icon: '✉️',
    accent: '#FBD75B',
    url: 'https://ai.arttechgroup.com:7777/coldemail/',
    tag: 'Generative',
    rating: 4.5,
    short: 'Generate personalized, high-converting outreach at scale.',
    tagline: 'Write personalized, high-converting cold emails in seconds — at scale.',
    tags: [{ label: 'New', type: 'green' }, { label: 'Generative', type: 'blue' }],
    whoFor: 'Sales, growth and founders who need consistent, personalized outreach without spending hours writing.',
    whatYouGet: 'A generator that crafts tailored emails, controls tone and templates, and builds smart follow-up sequences.',
    howItWorks: 'Paste a prospect or list and describe your offer — the agent drafts personalized emails and ready-to-send sequences.',
    featureGroups: [
      { title: 'Generation', items: ['Personalized at scale', 'Tone & style control', 'Reusable templates'] },
      { title: 'Outreach', items: ['Multi-step follow-ups', 'Subject-line variants', 'A/B-ready copy'] },
    ],
    useCases: [
      { title: 'Outbound campaigns', desc: 'Spin up a personalized campaign for a whole prospect list.', industry: 'Sales' },
      { title: 'Founder outreach', desc: 'Reach investors and partners with sharp, tailored emails.', industry: 'Startups' },
      { title: 'Re-engagement', desc: 'Win back cold leads with relevant follow-up sequences.', industry: 'Growth' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'Sales & Growth'],
      ['Complexity', 'Low'], ['Pricing', 'Free option'],
    ],
  },
  {
    name: 'Fintech Chatbot',
    slug: 'chatbot',
    icon: '💬',
    accent: '#E0A40C',
    url: 'https://ai.arttechgroup.com:7777/chatbot/',
    tag: 'Chatbot',
    rating: 4.7,
    short: 'Secure conversational AI built for fintech support.',
    tagline: 'A secure, always-on conversational assistant purpose-built for fintech.',
    tags: [{ label: 'Live', type: 'green' }, { label: 'Chatbot', type: 'blue' }],
    whoFor: 'Fintech and banking teams that need compliant, 24/7 customer support that can handle sensitive queries.',
    whatYouGet: 'A conversational assistant that answers customer questions, handles transactions and resolves multi-intent conversations.',
    howItWorks: 'Connect your product knowledge and policies — the bot responds securely, escalating to humans when needed.',
    featureGroups: [
      { title: 'Conversations', items: ['24/7 customer support', 'Multi-intent handling', 'Human handoff'] },
      { title: 'Security', items: ['Secure transaction queries', 'Compliance-aware replies', 'Audit logging'] },
    ],
    useCases: [
      { title: 'Customer support', desc: 'Resolve common queries instantly, reducing ticket volume.', industry: 'Fintech' },
      { title: 'Transaction help', desc: 'Guide users through payments, transfers and statements.', industry: 'Banking' },
      { title: 'Onboarding & KYC', desc: 'Answer onboarding questions and walk users through steps.', industry: 'Finance' },
    ],
    specs: [
      ['Deployment', 'Web / Embed'], ['Availability', 'Cloud'], ['Audience', 'Fintech'],
      ['Complexity', 'Medium'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'Unified Chatbot',
    slug: 'unified-chat',
    icon: '🤖',
    accent: '#FFD43B',
    url: 'https://ai.arttechgroup.com:7777/unified-chat',
    tag: 'Chatbot',
    rating: 4.6,
    short: 'One intelligent assistant across all of your channels.',
    tagline: 'Bring every conversation into one intelligent, context-aware assistant.',
    tags: [{ label: 'Featured', type: 'green' }, { label: 'Chatbot', type: 'blue' }],
    whoFor: 'Teams running support across multiple channels who want one consistent assistant and knowledge base.',
    whatYouGet: 'A single assistant that works across channels, shares one knowledge base, and keeps context everywhere.',
    howItWorks: 'Connect your channels and knowledge sources — the assistant serves consistent answers across all of them.',
    featureGroups: [
      { title: 'Omnichannel', items: ['One bot, every channel', 'Consistent answers', 'Context carries over'] },
      { title: 'Knowledge', items: ['Shared knowledge base', 'Live source sync', 'Smart routing'] },
    ],
    useCases: [
      { title: 'Unified support', desc: 'Answer customers the same way on web, chat and more.', industry: 'Support' },
      { title: 'Internal helpdesk', desc: 'Give employees one place to ask anything.', industry: 'Operations' },
      { title: 'Knowledge hub', desc: 'Turn scattered docs into instant answers.', industry: 'Enterprise' },
    ],
    specs: [
      ['Deployment', 'Web / Embed'], ['Availability', 'Cloud'], ['Audience', 'Enterprise'],
      ['Complexity', 'Medium'], ['Pricing', 'Free option'],
    ],
  },
  {
    name: 'Art Intelligence Platform',
    slug: 'art-intelligence',
    icon: '📊',
    accent: '#C8920A',
    url: 'https://ai.arttechgroup.com:7777/art-intelligence/dashboard',
    tag: 'Platform',
    rating: 4.8,
    short: 'Turn enterprise data into decisions with live analytics.',
    tagline: 'Turn raw enterprise data into decisions with real-time analytics and insights.',
    tags: [{ label: 'Featured', type: 'green' }, { label: 'Platform', type: 'blue' }],
    whoFor: 'Leaders and analysts who need a single, real-time view of their data to make faster decisions.',
    whatYouGet: 'A platform with real-time analytics, customizable dashboards and actionable, AI-generated insights.',
    howItWorks: 'Connect your data sources and build dashboards — the platform surfaces trends and insights automatically.',
    featureGroups: [
      { title: 'Analytics', items: ['Real-time metrics', 'Custom dashboards', 'Drill-down views'] },
      { title: 'Intelligence', items: ['AI-generated insights', 'Anomaly detection', 'Forecasting'] },
    ],
    useCases: [
      { title: 'Executive dashboards', desc: 'Give leadership a live view of the business.', industry: 'Enterprise' },
      { title: 'Operational reporting', desc: 'Replace manual reports with automated dashboards.', industry: 'Operations' },
      { title: 'Decision support', desc: 'Spot trends and act before they become problems.', industry: 'Strategy' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'Enterprise'],
      ['Complexity', 'Medium'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'FintechOps',
    slug: 'fintechops',
    icon: '⚙️',
    accent: '#EAB308',
    url: 'https://fintechops-arttechgroup.pages.dev/',
    tag: 'Operations',
    rating: 4.5,
    short: 'Automate and orchestrate your financial operations.',
    tagline: 'Streamline and orchestrate financial operations end-to-end.',
    tags: [{ label: 'Live', type: 'green' }, { label: 'Operations', type: 'blue' }],
    whoFor: 'Finance and operations teams that want to automate manual processes and monitor them in one place.',
    whatYouGet: 'Workflow automation, reconciliation and live operations monitoring across your financial processes.',
    howItWorks: 'Define your workflows and connect systems — FintechOps automates steps and flags exceptions in real time.',
    featureGroups: [
      { title: 'Automation', items: ['Workflow automation', 'Automated reconciliation', 'Exception handling'] },
      { title: 'Monitoring', items: ['Live ops dashboards', 'Alerts & SLAs', 'Audit trail'] },
    ],
    useCases: [
      { title: 'Reconciliation', desc: 'Match transactions automatically and surface mismatches.', industry: 'Finance' },
      { title: 'Process automation', desc: 'Remove repetitive manual steps from operations.', industry: 'Operations' },
      { title: 'Ops monitoring', desc: 'Track financial workflows live and catch issues early.', industry: 'Fintech' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'Finance Ops'],
      ['Complexity', 'Medium'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'Scheme Compliance Portal',
    slug: 'scheme-compliance-art',
    icon: '🛡️',
    accent: '#D9A41A',
    url: 'https://ai.arttechgroup.com:7777/scheme-compliance-art/login',
    tag: 'Compliance',
    rating: 4.7,
    short: 'End-to-end scheme compliance management — ART edition.',
    tagline: 'End-to-end scheme compliance management — the ART edition.',
    tags: [{ label: 'Secure', type: 'green' }, { label: 'Compliance', type: 'blue' }],
    whoFor: 'Compliance and risk teams managing schemes who need to track obligations and stay audit-ready.',
    whatYouGet: 'A portal to track compliance obligations, generate audit-ready reports and stay ahead of requirements.',
    howItWorks: 'Configure your schemes and obligations — the portal tracks status, deadlines and produces reports on demand.',
    featureGroups: [
      { title: 'Compliance', items: ['Obligation tracking', 'Deadline reminders', 'Status dashboards'] },
      { title: 'Reporting', items: ['Audit-ready reports', 'Evidence management', 'Role-based access'] },
    ],
    useCases: [
      { title: 'Obligation tracking', desc: 'Keep every requirement and deadline in one place.', industry: 'Compliance' },
      { title: 'Audit readiness', desc: 'Generate audit-ready reports in a few clicks.', industry: 'Risk' },
      { title: 'Scheme management', desc: 'Manage multiple schemes with role-based control.', industry: 'Governance' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'Compliance & Risk'],
      ['Complexity', 'Medium'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'Chargeback Management System',
    slug: 'chargeback-management-system',
    icon: '💳',
    accent: '#F5C010',
    url: 'https://chargeback-management-system.pages.dev/',
    tag: 'Finance',
    rating: 4.6,
    short: 'Track, manage and resolve payment chargebacks end-to-end.',
    tagline: 'Track, manage and resolve payment chargebacks and disputes in one place.',
    tags: [{ label: 'New', type: 'green' }, { label: 'Finance', type: 'blue' }],
    whoFor: 'Finance, payments and risk teams who need to handle chargebacks and disputes without losing track of deadlines.',
    whatYouGet: 'A system to log disputes, manage evidence, monitor status and resolve chargebacks faster.',
    howItWorks: 'Log incoming chargebacks, attach evidence and track each case through to resolution from a single dashboard.',
    featureGroups: [
      { title: 'Disputes', items: ['Case logging & tracking', 'Evidence management', 'Deadline reminders'] },
      { title: 'Insights', items: ['Status dashboards', 'Win-rate reporting', 'Reason-code analysis'] },
    ],
    useCases: [
      { title: 'Dispute resolution', desc: 'Manage every chargeback case from intake to outcome.', industry: 'Payments' },
      { title: 'Evidence management', desc: 'Keep all supporting documents organized per case.', industry: 'Finance' },
      { title: 'Loss reduction', desc: 'Improve win rates with reason-code insights and reporting.', industry: 'Risk' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'Finance & Payments'],
      ['Complexity', 'Medium'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'Incident Triage & RCA Agent',
    slug: 'incident-triage-rca',
    icon: '🚨',
    accent: '#E0A40C',
    url: '',
    tag: 'Operations',
    rating: 4.7,
    short: 'Detect, root-cause and suggest resolutions for production incidents end-to-end.',
    tagline: 'Detect, root-cause and resolve production incidents end-to-end — automatically.',
    tags: [{ label: 'New', type: 'green' }, { label: 'Operations', type: 'blue' }],
    whoFor: 'SRE, DevOps and platform teams who need to cut time-to-resolution and stop firefighting the same incidents.',
    whatYouGet: 'An agent that detects incidents, correlates signals into a root cause, and recommends concrete resolution steps.',
    howItWorks: 'Connect your logs, metrics and alerts — the agent triages incoming incidents, pinpoints the likely root cause and proposes fixes.',
    featureGroups: [
      { title: 'Triage', items: ['Automatic incident detection', 'Signal correlation', 'Severity & impact scoring'] },
      { title: 'Resolution', items: ['Root-cause analysis', 'Suggested remediations', 'Post-incident summaries'] },
    ],
    useCases: [
      { title: 'Faster RCA', desc: 'Surface the likely root cause in minutes instead of hours.', industry: 'SRE' },
      { title: 'Reduced downtime', desc: 'Triage and route incidents the moment they appear.', industry: 'DevOps' },
      { title: 'Post-mortems', desc: 'Generate clear incident timelines and summaries automatically.', industry: 'Platform' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'SRE & DevOps'],
      ['Complexity', 'Medium'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'KYC / KYB Client Onboarding Agent',
    slug: 'kyc-kyb-onboarding',
    icon: '🪪',
    accent: '#F5C010',
    url: '',
    tag: 'Compliance',
    rating: 4.7,
    short: 'Screen, verify and onboard new clients.',
    tagline: 'Screen, verify and onboard new clients with automated KYC and KYB checks.',
    tags: [{ label: 'New', type: 'green' }, { label: 'Compliance', type: 'blue' }],
    whoFor: 'Compliance, onboarding and risk teams who need to verify clients quickly without cutting corners on due diligence.',
    whatYouGet: 'An agent that screens individuals and businesses, runs verification checks and guides clients through onboarding.',
    howItWorks: 'Connect your verification and screening sources — the agent collects documents, runs KYC/KYB checks and flags risks for review.',
    featureGroups: [
      { title: 'Verification', items: ['Identity (KYC) checks', 'Business (KYB) checks', 'Document collection'] },
      { title: 'Screening', items: ['Sanctions & watchlist screening', 'Risk scoring', 'Audit-ready records'] },
    ],
    useCases: [
      { title: 'Faster onboarding', desc: 'Take new clients from application to approved in less time.', industry: 'Fintech' },
      { title: 'Risk screening', desc: 'Catch sanctioned or high-risk entities before they onboard.', industry: 'Compliance' },
      { title: 'Audit readiness', desc: 'Keep verifiable, audit-ready records for every client.', industry: 'Risk' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'Compliance & Onboarding'],
      ['Complexity', 'Medium'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'Reconciliation Agent',
    slug: 'reconciliation-agent',
    icon: '⚖️',
    accent: '#C8920A',
    url: '',
    tag: 'Finance',
    rating: 4.6,
    short: 'Detect, explain and clear unreconciled days.',
    tagline: 'Detect, explain and clear unreconciled days across your financial records.',
    tags: [{ label: 'New', type: 'green' }, { label: 'Finance', type: 'blue' }],
    whoFor: 'Finance and operations teams who spend hours chasing breaks and want reconciliation to clear itself.',
    whatYouGet: 'An agent that finds unreconciled days, explains the discrepancies and proposes the entries needed to clear them.',
    howItWorks: 'Connect your ledgers and statements — the agent matches transactions, isolates breaks and explains how to clear each one.',
    featureGroups: [
      { title: 'Detection', items: ['Automated matching', 'Break identification', 'Unreconciled-day alerts'] },
      { title: 'Resolution', items: ['Discrepancy explanations', 'Suggested adjustments', 'Clearing audit trail'] },
    ],
    useCases: [
      { title: 'Clear breaks faster', desc: 'Resolve unreconciled days in minutes, not hours.', industry: 'Finance' },
      { title: 'Explain discrepancies', desc: 'Understand exactly why a day failed to reconcile.', industry: 'Operations' },
      { title: 'Month-end close', desc: 'Walk into close with a clean, explained reconciliation.', industry: 'Accounting' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'Finance Ops'],
      ['Complexity', 'Medium'], ['Pricing', 'Contact sales'],
    ],
  },
  {
    name: 'Fraud Detection Agent',
    slug: 'fraud-detection',
    icon: '🛑',
    accent: '#EAB308',
    url: '',
    tag: 'Risk',
    rating: 4.8,
    short: 'Detect, flag and block fraudulent transactions.',
    tagline: 'Detect, flag and block fraudulent transactions in real time.',
    tags: [{ label: 'New', type: 'green' }, { label: 'Risk', type: 'blue' }],
    whoFor: 'Risk, payments and fraud teams who need to stop fraudulent transactions before they settle.',
    whatYouGet: 'An agent that scores transactions for fraud, flags suspicious activity and blocks high-risk payments automatically.',
    howItWorks: 'Connect your transaction stream — the agent scores each payment in real time, flags anomalies and blocks high-risk transactions.',
    featureGroups: [
      { title: 'Detection', items: ['Real-time transaction scoring', 'Anomaly detection', 'Behavioral patterns'] },
      { title: 'Response', items: ['Automatic blocking', 'Risk-based flagging', 'Case audit trail'] },
    ],
    useCases: [
      { title: 'Stop fraud early', desc: 'Block high-risk transactions before they settle.', industry: 'Payments' },
      { title: 'Reduce false positives', desc: 'Flag genuine threats without blocking good customers.', industry: 'Risk' },
      { title: 'Investigation support', desc: 'Give analysts a clear audit trail for every flagged case.', industry: 'Fraud' },
    ],
    specs: [
      ['Deployment', 'Web app'], ['Availability', 'Cloud'], ['Audience', 'Risk & Payments'],
      ['Complexity', 'Medium'], ['Pricing', 'Contact sales'],
    ],
  },
]
